### ISSUE TITLE
Skip Pushes to Apple News By Default

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/wp-bulk-task#32] opened 2024-07-10 16:59 UTC
### Description

Disable pushes to Apple News by default when running a bulk task. Allow this behavior to be overridden (so updates _can_ be sent to Apple News, if desired).

### Use Case

When running a bulk task, updates performed to posts should not be automatically synced to Apple News, because it can create a flood of requests and potentially result in rate-limiting.

**Comment by renatonascalves** [comment] 2024-07-10 20:48
@kevinfodness  Had you have a chance to look at our custom trait? It was designed to support this scenario too.

https://github.com/alleyinteractive/wp-bulk-task/blob/6772f7ab6abd5e1209ba5b80fb37cf6a6cf1e33d/src/trait-bulk-task-side-effects.php#L23

> Allow this behavior to be overridden (so updates can be sent to Apple News, if desired).

Since the goal seems to be to change the order to disable by default, it'd be good to update this trait too to account for this change in behavior.

**Comment by anubisthejackle** [comment] 2024-07-30 14:28
@kevinfodness Given the trait covers skipping Apple News pushes, and @mboynes comment on PR #35 , should we close this?

**Closed as completed** 2024-08-14 18:19 UTC
Labels: enhancement, wontfix, php
